import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ta' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    welcome: 'Welcome back',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    available: 'Available',
    unavailable: 'Unavailable',
    toggleStatus: 'Toggle Status',
    overview: 'Overview',
    appointments: 'Appointments',
    patients: 'Patients',
    hospitalInfo: 'Hospital Info',
    profile: 'Profile',
    todayAppointments: "Today's Appointments",
    totalPatients: 'Total Patients',
    pendingReviews: 'Pending Reviews',
    availableBeds: 'Available Beds',
    bedManagement: 'Bed Availability Management',
    icuBeds: 'ICU Beds',
    emergencyBeds: 'Emergency Beds',
    generalWard: 'General Ward',
    occupied: 'Occupied',
    bloodInventory: 'Blood Inventory',
    selectBloodType: 'Select Blood Type',
    availableUnits: 'Available Units',
    lastUpdated: 'Last Updated',
    todaySchedule: "Today's Schedule",
    noAppointments: 'No appointments scheduled for today',
    doctorProfile: 'Doctor Profile',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    professionalInfo: 'Professional Information',
    specialization: 'Specialization',
    experience: 'Experience',
    years: 'years',
    consultationFee: 'Consultation Fee',
    contactInfo: 'Contact Information',
    phone: 'Phone',
    hospital: 'Hospital',
    department: 'Department',
    notSet: 'Not set',
    home: 'Home',
    findDoctor: 'Find a Doctor',
    bookAppointment: 'Book Appointment',
    bloodBank: 'Blood Bank',
    emergencyServices: 'Emergency Services',
    myAppointments: 'My Appointments',
    medicalRecords: 'Medical Records',
    symptoms: 'Symptoms',
    enterSymptoms: 'Enter your symptoms',
    searchDoctors: 'Search Doctors',
    searchHospitals: 'Search Hospitals',
    nearbyHospitals: 'Nearby Hospitals',
    topDoctors: 'Top Rated Doctors',
    upcomingAppointments: 'Upcoming Appointments',
    completed: 'Completed',
    confirmed: 'Confirmed',
    pending: 'Pending',
    cancelled: 'Cancelled',
    viewDetails: 'View Details',
    reschedule: 'Reschedule',
    appointmentWith: 'Appointment with',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    adminDashboard: 'Admin Dashboard',
    hospitalManagement: 'Hospital Management',
    doctorManagement: 'Doctor Management',
    statistics: 'Statistics',
    totalDoctors: 'Total Doctors',
    totalAppointments: 'Total Appointments',
    activeDoctors: 'Active Doctors',
    hospitalDetails: 'Hospital Details',
    name: 'Name',
    address: 'Address',
    email: 'Email',
    deanName: 'Dean Name',
    licenseNo: 'License No',
    totalBeds: 'Total Beds',
    bedAvailability: 'Bed Availability',
    icu: 'ICU',
    emergency: 'Emergency',
    general: 'General',
    rating: 'Rating',
    fee: 'Fee',
    selectSpecialization: 'Select Specialization',
    selectHospital: 'Select Hospital',
    generalMedicine: 'General Medicine',
    cardiology: 'Cardiology',
    neurology: 'Neurology',
    orthopedics: 'Orthopedics',
    pediatrics: 'Pediatrics',
    surgery: 'Surgery',
    dermatology: 'Dermatology',
    psychiatry: 'Psychiatry',
    language: 'Language',
    english: 'English',
    tamil: 'தமிழ்',
    hindi: 'हिंदी',
  },
  ta: {
    welcome: 'மீண்டும் வரவேற்கிறோம்',
    logout: 'வெளியேறு',
    deleteAccount: 'கணக்கை நீக்கு',
    available: 'கிடைக்கிறது',
    unavailable: 'கிடைக்கவில்லை',
    toggleStatus: 'நிலையை மாற்று',
    overview: 'கண்ணோட்டம்',
    appointments: 'சந்திப்புகள்',
    patients: 'நோயாளிகள்',
    hospitalInfo: 'மருத்துவமனை தகவல்',
    profile: 'சுயவிவரம்',
    todayAppointments: 'இன்றைய சந்திப்புகள்',
    totalPatients: 'மொத்த நோயாளிகள்',
    pendingReviews: 'நிலுவையில் உள்ள மதிப்பாய்வுகள்',
    availableBeds: 'கிடைக்கும் படுக்கைகள்',
    bedManagement: 'படுக்கை கிடைக்கும் மேலாண்மை',
    icuBeds: 'ஐசியூ படுக்கைகள்',
    emergencyBeds: 'அவசர படுக்கைகள்',
    generalWard: 'பொது வார்டு',
    occupied: 'ஆக்கிரமிக்கப்பட்டது',
    bloodInventory: 'இரத்த சரக்கு',
    selectBloodType: 'இரத்த வகையைத் தேர்ந்தெடுக்கவும்',
    availableUnits: 'கிடைக்கும் அலகுகள்',
    lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    todaySchedule: 'இன்றைய அட்டவணை',
    noAppointments: 'இன்று எந்த சந்திப்பும் திட்டமிடப்படவில்லை',
    doctorProfile: 'மருத்துவர் சுயவிவரம்',
    edit: 'திருத்து',
    save: 'சேமி',
    cancel: 'ரத்துசெய்',
    professionalInfo: 'தொழில்முறை தகவல்',
    specialization: 'நிபுணத்துவம்',
    experience: 'அனுபவம்',
    years: 'ஆண்டுகள்',
    consultationFee: 'ஆலோசனை கட்டணம்',
    contactInfo: 'தொடர்பு தகவல்',
    phone: 'தொலைபேசி',
    hospital: 'மருத்துவமனை',
    department: 'துறை',
    notSet: 'அமைக்கப்படவில்லை',
    home: 'முகப்பு',
    findDoctor: 'மருத்துவரைக் கண்டறியவும்',
    bookAppointment: 'சந்திப்பு பதிவு செய்க',
    bloodBank: 'இரத்த வங்கி',
    emergencyServices: 'அவசர சேவைகள்',
    myAppointments: 'எனது சந்திப்புகள்',
    medicalRecords: 'மருத்துவ பதிவுகள்',
    symptoms: 'அறிகுறிகள்',
    enterSymptoms: 'உங்கள் அறிகுறிகளை உள்ளிடவும்',
    searchDoctors: 'மருத்துவர்களைத் தேடுங்கள்',
    searchHospitals: 'மருத்துவமனைகளைத் தேடுங்கள்',
    nearbyHospitals: 'அருகிலுள்ள மருத்துவமனைகள்',
    topDoctors: 'சிறந்த மருத்துவர்கள்',
    upcomingAppointments: 'வரவிருக்கும் சந்திப்புகள்',
    completed: 'முடிந்தது',
    confirmed: 'உறுதிப்படுத்தப்பட்டது',
    pending: 'நிலுவையில்',
    cancelled: 'ரத்து செய்யப்பட்டது',
    viewDetails: 'விவரங்களைக் காண்க',
    reschedule: 'மறுதிட்டமிடல்',
    appointmentWith: 'சந்திப்பு',
    date: 'தேதி',
    time: 'நேரம்',
    status: 'நிலை',
    adminDashboard: 'நிர்வாக டாஷ்போர்டு',
    hospitalManagement: 'மருத்துவமனை மேலாண்மை',
    doctorManagement: 'மருத்துவர் மேலாண்மை',
    statistics: 'புள்ளிவிவரங்கள்',
    totalDoctors: 'மொத்த மருத்துவர்கள்',
    totalAppointments: 'மொத்த சந்திப்புகள்',
    activeDoctors: 'செயலில் உள்ள மருத்துவர்கள்',
    hospitalDetails: 'மருத்துவமனை விவரங்கள்',
    name: 'பெயர்',
    address: 'முகவரி',
    email: 'மின்னஞ்சல்',
    deanName: 'டீன் பெயர்',
    licenseNo: 'உரிமம் எண்',
    totalBeds: 'மொத்த படுக்கைகள்',
    bedAvailability: 'படுக்கை கிடைக்கும் தன்மை',
    icu: 'ஐசியூ',
    emergency: 'அவசரம்',
    general: 'பொது',
    rating: 'மதிப்பீடு',
    fee: 'கட்டணம்',
    selectSpecialization: 'நிபுணத்துவத்தைத் தேர்ந்தெடுக்கவும்',
    selectHospital: 'மருத்துவமனையைத் தேர்ந்தெடுக்கவும்',
    generalMedicine: 'பொது மருத்துவம்',
    cardiology: 'இதய மருத்துவம்',
    neurology: 'நரம்பியல்',
    orthopedics: 'எலும்பியல்',
    pediatrics: 'குழந்தை மருத்துவம்',
    surgery: 'அறுவை சிகிச்சை',
    dermatology: 'தோல் மருத்துவம்',
    psychiatry: 'மனநல மருத்துவம்',
    language: 'மொழி',
    english: 'English',
    tamil: 'தமிழ்',
    hindi: 'हिंदी',
  },
  hi: {
    welcome: 'वापस स्वागत है',
    logout: 'लॉग आउट',
    deleteAccount: 'खाता हटाएं',
    available: 'उपलब्ध',
    unavailable: 'अनुपलब्ध',
    toggleStatus: 'स्थिति बदलें',
    overview: 'अवलोकन',
    appointments: 'अपॉइंटमेंट',
    patients: 'मरीज़',
    hospitalInfo: 'अस्पताल की जानकारी',
    profile: 'प्रोफ़ाइल',
    todayAppointments: 'आज की अपॉइंटमेंट',
    totalPatients: 'कुल मरीज़',
    pendingReviews: 'लंबित समीक्षाएं',
    availableBeds: 'उपलब्ध बिस्तर',
    bedManagement: 'बिस्तर उपलब्धता प्रबंधन',
    icuBeds: 'आईसीयू बिस्तर',
    emergencyBeds: 'आपातकालीन बिस्तर',
    generalWard: 'सामान्य वार्ड',
    occupied: 'व्याप्त',
    bloodInventory: 'रक्त भंडार',
    selectBloodType: 'रक्त समूह चुनें',
    availableUnits: 'उपलब्ध इकाइयां',
    lastUpdated: 'अंतिम अपडेट',
    todaySchedule: 'आज का कार्यक्रम',
    noAppointments: 'आज कोई अपॉइंटमेंट निर्धारित नहीं है',
    doctorProfile: 'डॉक्टर प्रोफ़ाइल',
    edit: 'संपादित करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    professionalInfo: 'व्यावसायिक जानकारी',
    specialization: 'विशेषज्ञता',
    experience: 'अनुभव',
    years: 'वर्ष',
    consultationFee: 'परामर्श शुल्क',
    contactInfo: 'संपर्क जानकारी',
    phone: 'फ़ोन',
    hospital: 'अस्पताल',
    department: 'विभाग',
    notSet: 'सेट नहीं',
    home: 'होम',
    findDoctor: 'डॉक्टर खोजें',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    bloodBank: 'रक्त बैंक',
    emergencyServices: 'आपातकालीन सेवाएं',
    myAppointments: 'मेरी अपॉइंटमेंट',
    medicalRecords: 'चिकित्सा रिकॉर्ड',
    symptoms: 'लक्षण',
    enterSymptoms: 'अपने लक्षण दर्ज करें',
    searchDoctors: 'डॉक्टर खोजें',
    searchHospitals: 'अस्पताल खोजें',
    nearbyHospitals: 'आस-पास के अस्पताल',
    topDoctors: 'शीर्ष डॉक्टर',
    upcomingAppointments: 'आगामी अपॉइंटमेंट',
    completed: 'पूर्ण',
    confirmed: 'पुष्टि की गई',
    pending: 'लंबित',
    cancelled: 'रद्द',
    viewDetails: 'विवरण देखें',
    reschedule: 'पुनर्निर्धारण',
    appointmentWith: 'अपॉइंटमेंट',
    date: 'तारीख',
    time: 'समय',
    status: 'स्थिति',
    adminDashboard: 'व्यवस्थापक डैशबोर्ड',
    hospitalManagement: 'अस्पताल प्रबंधन',
    doctorManagement: 'डॉक्टर प्रबंधन',
    statistics: 'सांख्यिकी',
    totalDoctors: 'कुल डॉक्टर',
    totalAppointments: 'कुल अपॉइंटमेंट',
    activeDoctors: 'सक्रिय डॉक्टर',
    hospitalDetails: 'अस्पताल विवरण',
    name: 'नाम',
    address: 'पता',
    email: 'ईमेल',
    deanName: 'डीन का नाम',
    licenseNo: 'लाइसेंस नंबर',
    totalBeds: 'कुल बिस्तर',
    bedAvailability: 'बिस्तर उपलब्धता',
    icu: 'आईसीयू',
    emergency: 'आपातकाल',
    general: 'सामान्य',
    rating: 'रेटिंग',
    fee: 'शुल्क',
    selectSpecialization: 'विशेषज्ञता चुनें',
    selectHospital: 'अस्पताल चुनें',
    generalMedicine: 'सामान्य चिकित्सा',
    cardiology: 'हृदय रोग विज्ञान',
    neurology: 'न्यूरोलॉजी',
    orthopedics: 'आर्थोपेडिक्स',
    pediatrics: 'बाल चिकित्सा',
    surgery: 'शल्य चिकित्सा',
    dermatology: 'त्वचा विज्ञान',
    psychiatry: 'मनोचिकित्सा',
    language: 'भाषा',
    english: 'English',
    tamil: 'தமிழ்',
    hindi: 'हिंदी',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('hwm_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('hwm_language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
